### ISSUE TITLE
Broken in ember-cli 3.5+

### ISSUE THREAD

**Issue by nickschot** [Appchance/ember-cached-shoe#5]
Probably due to breaking changes in broccoli 2.

See: https://github.com/ember-cli/ember-cli/issues/8140

**Comment by The-Don-Himself** [comment]
Yep, also running into this

````  - errorMessage: null
        at WebpackWriter
-~- created here: -~-
    at WebpackWriter.Plugin (/builds/campus-discounts/ember.js/node_modules/broccoli-webpack/node_modules/broccoli-plugin/index.js:10:31)
    at WebpackWriter.CachingWriter [as constructor] (/builds/campus-discounts/ember.js/node_modules/broccoli-webpack/node_modules/broccoli-caching-writer/index.js:18:10)
    at new WebpackWriter (/builds/campus-discounts/ember.js/node_modules/broccoli-webpack/index.js:13:16)
    at Class.processTree (/builds/campus-discounts/ember.js/node_modules/ember-cached-shoe/index.js:26:21)
    at processedTree (/builds/campus-discounts/ember.js/node_modules/ember-cli-node-assets/lib/tree-for.js:40:43)
````

**Comment by Uysim** [comment]
+1

**Comment by williamweckl** [comment]
Any updates on this?

**Comment by HarenBroog** [comment]
I will look at this problem this week guys. It seems like easy to fix ;)

**Comment by catz** [comment]
Have a look at my proposal
https://github.com/catz/ember-cached-shoe/commit/dec55e8a6c167e2d0a37751b34765d33a5d52e5d

**Comment by HarenBroog** [comment]
@marucjmar any progress with this?

**Comment by marucjmar** [comment]
@HarenBroog  I'm testing a new solution on the branch `feature/ember-cli-3.5-support`

**Comment by williamweckl** [comment]
@marucjmar Thanks for the amazing work! Is the branch `feature/ember-cli-3.5-support` safe to use in production? I want to update my ember.js but this library is the only one thats stoping me to do that.

**Comment by fiddler** [comment]
I've tried the branch and it seems to crash when your fields contain emojis for example with the following error:

`VM155 vendor-21373b1980f05b0d9b9a23fc78de534e.js:1781 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`

On a quick peek it looks like the earlier version was using https://github.com/kaelzhang/b2a to get around these issues. @marucjmar might consider using that in the branch too? :)

I managed to make it work by monkey patching in a replacement function for btoa, which does not die with unicode characters.

**Comment by adambedford** [comment]
Any progress on this?

**Comment by danwenzel** [comment]
This is blocking us as well.  @HarenBroog @marucjmar - Any updates?

**Comment by marucjmar** [comment]
Close with PR #7  
should be used `0.2.0` version

**Comment by danwenzel** [comment]
`0.2.0` solved the issue for us.  Thank you!
