### ISSUE TITLE
Does not work with ember-fetch

### ISSUE THREAD

**Issue by chrism** [Appchance/ember-cached-shoe#6]
Hi,

This addon works perfectly when used with the standard ajax requests like this:

```js
import DS from 'ember-data';
import CachedShoe from 'ember-cached-shoe';

export default DS.JSONAPIAdapter.extend(CachedShoe {
});
```

But not when used together with the `ember-fetch` [adapter mixin](https://github.com/ember-cli/ember-fetch#use-with-ember-data).

```js
import DS from 'ember-data';
import AdapterFetch from 'ember-fetch/mixins/adapter-fetch';
import CachedShoe from 'ember-cached-shoe';

export default DS.JSONAPIAdapter.extend(CachedShoe, AdapterFetch {
});
```
As Ember Data adopts fetch and removes jQuery is this something that should be supported?

Thanks!

**Comment by chrism** [comment]
Sorry, this was an issue with the ordering, by putting AdapterFetch first it seems to work.

**Comment by HarenBroog** [comment]
I am happy it helped ;)
